modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="mystical_flower"
version="0.0.1"
displayName="Mystical Flower"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="CoringPlay472, MCreator"

[[dependencies.mystical_flower]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"



[[dependencies.mystical_flower]]
    modId="crafttweaker"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mystical_flower]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

